name: Cloud Compliance Report Export

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # 6:30 AM IST daily

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CSPM Report
        id: cspm
        uses: ./.github/actions
        with:
          cspm_access_token: ${{ secrets.CSPM_ACCESS_TOKEN }}
          account_id: "408357780127"
          toolkit_base_url: "https://toolkit.demo.accuknox.com"
          report_name: "CSPM Report"
          ticket_summary: "true"
          asset_summary: "true"
          report_type: "Compliance"
          compliance_program: "AWS CIS Benchmark v4.0.1"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cspm-report
          path: ${{ steps.cspm.outputs.report_path }}
